apiVersion: v1
kind: Namespace
metadata:
  name: nexora
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nexora-ingress
  namespace: nexora
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "300"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "300"
spec:
  ingressClassName: nginx
  rules:
    - host: nexora.example.com
      http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: nexora-backend
                port:
                  number: 80
          - path: /actuator
            pathType: Prefix
            backend:
              service:
                name: nexora-backend
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nexora-frontend
                port:
                  number: 80
  tls:
    - hosts:
        - nexora.example.com
      secretName: nexora-tls-secret
