apiVersion: v1
kind: Secret
metadata:
  name: nexora-secrets
  namespace: nexora
type: Opaque
stringData:
  db-host: "postgres.default.svc.cluster.local"
  db-name: "nexora"
  db-username: "nexora"
  db-password: "replace-with-strong-password"
  redis-host: "redis.default.svc.cluster.local"
  kafka-bootstrap-servers: "kafka.default.svc.cluster.local:9092"
  jwt-secret: "replace-with-a-very-long-random-secret"
